# Домашнее задание 2 (5 баллов).

Все задания ниже имеют равный вес (5/16).

In [4]:
import pandas as pd

#### Описание данных

В папке Dat (https://github.com/hse-ds/iad-intro-ds/blob/master/2023/homeworks/Data.zip) находится информация о студентах. Всего 10 групп студентов. Файлы делятся на две категории:
    * Students_info_i - информация о студентах из группы i
    * Students_marks_i - оценки студентов из группы i за экзамены

### Одно из важных достоинств pandas $-$ это удобные методы реляционного взаимодействия с данными, аналогичные, например, возможностям SQL для слияния и конкатенации таблиц: merge, join, concat. Наличие готовых методов позволяет не реализовывать самостоятельно поэлементную обработку данных и оперировать сразу целыми таблицами данных.

Подробно об этих методах посмотрите тут: https://www.kaggle.com/residentmario/renaming-and-combining#Combining

#### Задание 1. Соберите всю информацию о студентах в одну таблицу df. В получившейся таблице должна быть информация и оценки всех студентов из всех групп. Напечатайте несколько строк таблицы для демонстрации результата.¶

In [5]:
info = pd.concat([pd.read_csv(f'Students_info_{i}.csv') for i in range(10)])
marks = pd.concat([pd.read_csv(f'Students_marks_{i}.csv') for i in range(10)])
df = info.merge(marks)

df.head(1000)

,index,gender,race/ethnicity,parental level of education,lunch,test preparation course,group,math score,reading score,writing score
0,0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,1,female,group C,some college,standard,completed,group1,69,90,88
2,2,female,group B,master's degree,standard,none,group1,90,95,93
3,3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,4,male,group C,some college,standard,none,group1,76,78,75
...,...,...,...,...,...,...,...,...,...,...
995,995,female,group E,master's degree,standard,completed,group10,88,99,95
996,996,male,group C,high school,free/reduced,none,group10,62,55,55
997,997,female,group C,high school,free/reduced,completed,group10,59,71,65
998,998,female,group D,some college,standard,completed,group10,68,78,77
999,999,female,group D,some college,free/reduced,none,group10,77,86,86

#### Задание 2. Удалите столбец index у полученной таблицы. Напечатайте первые 10 строк таблицы.

In [7]:
df = df.drop("index", axis = 1)
df.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,group,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,female,group C,some college,standard,completed,group1,69,90,88
2,female,group B,master's degree,standard,none,group1,90,95,93
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,male,group C,some college,standard,none,group1,76,78,75
5,female,group B,associate's degree,standard,none,group1,71,83,78
6,female,group B,some college,standard,completed,group1,88,95,92
7,male,group B,some college,free/reduced,none,group1,40,43,39
8,male,group D,high school,free/reduced,completed,group1,64,64,67
9,female,group B,high school,free/reduced,none,group1,38,60,50

#### Задание 3. Выведите на экран размеры полученной таблицы

In [8]:
df.shape

(1000, 9)

#### Задание 4. Выведите на экран статистические характеристики числовых столбцов таблицы (минимум, максимум, среднее значение, стандартное отклонение)

In [9]:
df.describe().drop(['25%', '50%', '75%'])

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
max     100.00000     100.000000     100.000000

#### Задание 5. Проверьте, есть ли в таблице пропущенные значения

In [10]:
df.isnull().any().any()

False

#### Задание 6. Выведите на экран средние баллы студентов по каждому предмету (math, reading, writing)

In [11]:
df[['math score', 'reading score', 'writing score']].mean()

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

**Задание 7. Как зависят оценки от того, проходил ли студент курс для подготовки к сдаче экзамена (test preparation course)? Выведите на экран для каждого предмета в отдельности средний балл студентов, проходивших курс для подготовки к экзамену и не проходивших курс.**

In [12]:
df.groupby('test preparation course').mean(numeric_only=True)

                         math score  reading score  writing score
test preparation course
completed                 69.695531      73.893855      74.418994
none                      64.077882      66.534268      64.504673

---
Вывод

Оценки по каждому предмету у студентов, проходивших курс для подготовки к экзамену,заметно выше, чем у не проходивших курс

---

In [13]:
completed_course = df[df['test preparation course'] == 'completed']
completed_course_score = completed_course[['math score', 'reading score', 'writing score']]
completed_course_average_score = completed_course_score.mean()

no_course = df[df['test preparation course'] != 'completed']
no_course_score = no_course[['math score', 'reading score', 'writing score']]
no_course_average_score = no_course_score.mean()

print('completed course')
for val in completed_course_average_score.values:
  print(val)

print('\ndidn\'t complete course')
for val in no_course_average_score:
    print(val)

completed course
69.69553072625699
73.89385474860335
74.41899441340782

didn't complete course
64.0778816199377
66.53426791277259
64.50467289719626

**Задание 8. Выведите на экран все различные значения из столбца lunch.**

In [14]:
print(df['lunch'].unique())

['standard' 'free/reduced']

In [15]:
df['lunch'].drop_duplicates()

0        standard
3    free/reduced
Name: lunch, dtype: object

**Задание 9. Переименуйте колонку "parental level of education" в "education", а "test preparation course" в "test preparation" с помощью метода pandas rename**
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html

In [16]:
df = df.rename(columns = {"parental level of education" : "education", "test preparation course" : "test preparation"})
df

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,female,group C,some college,standard,completed,group1,69,90,88
2,female,group B,master's degree,standard,none,group1,90,95,93
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,male,group C,some college,standard,none,group1,76,78,75
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,group10,88,99,95
996,male,group C,high school,free/reduced,none,group10,62,55,55
997,female,group C,high school,free/reduced,completed,group10,59,71,65
998,female,group D,some college,standard,completed,group10,68,78,77
999,female,group D,some college,free/reduced,none,group10,77,86,86

**Зафиксируем минимальный балл для сдачи экзамена**

In [17]:
passmark = 50

**Задание 10. Ответьте на вопросы:**
    * Какая доля студентов сдала экзамен по математике (passmark >= 50)?
    * Какая доля студентов, проходивших курс подготовки к экзамену, сдала экзамен по математике?
    * Какая доля женщин, не проходивших курс подготовки к экзамену, не сдала экзамен по математике?

In [18]:
passed = df[df['math score'] >= passmark].count()[0]
total = df.count()[0]
print(f"Passed exam: {passed / total}")

Passed exam: 0.865

In [19]:
completed_course_passed = df[(df['test preparation'] == 'completed') & (df['math score'] >= passmark)].count()[0]
total = df.count()[0]
print(f"Passed exam with course: {completed_course_passed / total}")

Passed exam with course: 0.33

In [20]:
female_relevant = df[(df['gender'] == 'female') & (df['test preparation'] == 'none') & (df['math score'] < passmark)].count()[0]
female_total = df[(df['gender'] == 'female')].count()[0]
print(f"Females not passed exam no course: {female_relevant / female_total}")

Females not passed exam no course: 0.13513513513513514

**Задание 11. С помощью groupby выполните задания ниже. Также выведите время выполнения каждого из заданий.**
    * Для каждой этнической группы выведите средний балл за экзамен по чтению
    * Для каждого уровня образования выведите минимальный балл за экзамен по письму

In [21]:
import time

In [22]:
time_start = time.time()
reading_scores_by_ethnicity = df.groupby('race/ethnicity')['reading score'].mean()
print(reading_scores_by_ethnicity)
print(f"\nTime elapsed: {time.time() - time_start}")

race/ethnicity
group A    64.674157
group B    67.352632
group C    69.103448
group D    70.030534
group E    73.028571
Name: reading score, dtype: float64

Time elapsed: 0.0070683956146240234

In [23]:
time_start = time.time()
writing_scores_by_education = df.groupby('education')['writing score'].min()
print(writing_scores_by_education)
print(f"\nTime elapsed: {time.time() - time_start}")

education
associate's degree    35
bachelor's degree     38
high school           15
master's degree       46
some college          19
some high school      10
Name: writing score, dtype: int64

Time elapsed: 0.0038013458251953125

**Задание 12. Выполните задание 11 с помощью циклов. Сравните время выполнения.**

In [24]:
time_start = time.time()

print("ethnicity")
for i in df['race/ethnicity'].sort_values().unique():
  reading_scores_by_ethnicity = df[df['race/ethnicity'] == i]['reading score'].mean()
  print(f"{i}    {reading_scores_by_ethnicity}")

print(f"\nTime elapsed: {time.time() - time_start}")

ethnicity
group A    64.67415730337079
group B    67.35263157894737
group C    69.10344827586206
group D    70.03053435114504
group E    73.02857142857142

Time elapsed: 0.015718936920166016

In [25]:
time_start = time.time()

print("education")
for i in df['education'].sort_values().unique():
  education = i
  while len(education) != 22: education += ' '
  writing_score_by_education = df[df['education'] == i]['writing score'].min()
  print(education + f"{writing_score_by_education}")

print(f"\nTime elapsed: {time.time() - time_start}")

education
associate's degree    35
bachelor's degree     38
high school           15
master's degree       46
some college          19
some high school      10

Time elapsed: 0.023434162139892578

**Задание 13. Выведите на экран средние баллы студентов по каждому предмету в зависимости от пола и уровня образования. То есть должно получиться количество групп, равных 2 * (число уровней образования), и для каждой такой группы выыведите средний балл по каждому из предметов.**

Это можно сделать с помощью сводных таблиц (pivot_table):

https://www.kaggle.com/kamilpolak/tutorial-how-to-use-pivot-table-in-pandas

In [26]:
pd.pivot_table(df, values = ['math score', 'reading score', 'writing score'], index = ['gender','education'])

                           math score  reading score  writing score
gender education
female associate's degree   65.250000      74.120690      74.000000
       bachelor's degree    68.349206      77.285714      78.380952
       high school          59.351064      68.202128      66.691489
       master's degree      66.500000      76.805556      77.638889
       some college         65.406780      73.550847      74.050847
       some high school     59.296703      69.109890      68.285714
male   associate's degree   70.764151      67.433962      65.405660
       bachelor's degree    70.581818      68.090909      67.654545
       high school          64.705882      61.480392      58.539216
       master's degree      74.826087      73.130435      72.608696
       some college         69.009259      64.990741      63.148148
       some high school     67.840909      64.693182      61.375000

#### Задание 14. Сколько студентов успешно сдали экзамен по математике?

Создайте новый столбец в таблице df под названием Math_PassStatus и запишите в него F, если студент не сдал экзамен по математике (балл за экзамен < passmark), и P иначе.

Посчитайте количество студентов, сдавших и не сдавших экзамен по математике.

Сделайте аналогичные шаги для экзаменов по чтению и письму.

In [27]:
def main(mark):
  if mark >= passmark:
    return 'P'
  return 'F'

In [28]:
df['Math_PassStatus'] = df['math score'].apply(main)
passed_maths_count = df[df['Math_PassStatus'] == 'P'].count()[0]
failed_maths_count = df[df['Math_PassStatus'] == 'F'].count()[0]
print(f'Passed Math: {passed_maths_count}')
print(f'Failed Math: {failed_maths_count}')

Passed Math: 865
Failed Math: 135

In [29]:
df['Reading_PassStatus'] = df['reading score'].apply(main)
passed_reading_count = df[df['Reading_PassStatus'] == 'P'].count()[0]
failed_reading_count = df[df['Reading_PassStatus'] == 'F'].count()[0]
print(f'Passed Reading: {passed_reading_count}')
print(f'Failed Reading: {failed_reading_count}')

Passed Reading: 910
Failed Reading: 90

In [30]:
df['Writing_PassStatus'] = df['math score'].apply(main)
passed_writing_count = df[df['Writing_PassStatus'] == 'P'].count()[0]
failed_writing_count = df[df['Writing_PassStatus'] == 'F'].count()[0]
print(f'Passed Writing: {passed_writing_count}')
print(f'Failed Writing: {failed_writing_count}')

Passed Writing: 865
Failed Writing: 135

#### Задание 15. Сколько студентов успешно сдали все экзамены?

Создайте столбец OverAll_PassStatus и запишите в него для каждого студента 'F', если студент не сдал хотя бы один из трех экзаменов, а иначе 'P'.

Посчитайте количество студентов, которые сдали все экзамены.

In [31]:
df['OverAll_PassStatus'] = df.apply(lambda x: 'P' if x['Math_PassStatus'] == 'P' and x['Reading_PassStatus'] == 'P' and x['Writing_PassStatus'] == 'P' else 'F', axis = 1)
passed_count = df[df['OverAll_PassStatus'] == 'P'].count()[0]
print(f'Passed All: {passed_count}')

Passed All: 834

#### Задание 16. Переведем баллы в оценки

### Система перевода баллов в оценки
####    больше 90 = A
####      80-90 = B
####      70-80 = C
####      60-70 = D
####      50-60 = E
####    меньше 50 = F (Fail)

Создайте вспомогательную функцию, которая будет по среднему баллу за три экзамена выставлять оценку студенту по данным выше критериям.

Создайте столбец Grade и запишите в него оценку каждого студента.

Выведите количество студентов, получивших каждую из оценок.

**В случае, если средний балл попадает на границу между оценками (т.е. равен ровно 60, 70 или 80 баллов), вы можете интерпретировать условие на своё усмотрение (т.е. можете поставить за 60 баллов оценку D, а можете - E).**

In [32]:
def GetGrade(average_mark):
  if average_mark >= 90:
    return 'A'
  elif 80 <= average_mark < 90:
    return 'B'
  elif 70 <= average_mark < 80:
    return 'C'
  elif 60 <= average_mark < 70:
    return 'D'
  elif 50 <= average_mark < 60:
    return 'E'
  return 'F'

In [33]:
df['Grade'] = df[['math score', 'reading score', 'writing score']].mean(axis=1).apply(GetGrade)
df

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score,Math_PassStatus,Reading_PassStatus,Writing_PassStatus,OverAll_PassStatus,Grade
0,female,group B,bachelor's degree,standard,none,group1,72,72,74,P,P,P,P,C
1,female,group C,some college,standard,completed,group1,69,90,88,P,P,P,P,B
2,female,group B,master's degree,standard,none,group1,90,95,93,P,P,P,P,A
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44,F,P,F,F,F
4,male,group C,some college,standard,none,group1,76,78,75,P,P,P,P,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,group10,88,99,95,P,P,P,P,A
996,male,group C,high school,free/reduced,none,group10,62,55,55,P,P,P,P,E
997,female,group C,high school,free/reduced,completed,group10,59,71,65,P,P,P,P,D
998,female,group D,some college,standard,completed,group10,68,78,77,P,P,P,P,C
999,female,group D,some college,free/reduced,none,group10,77,86,86,P,P,P,P,B

In [51]:
df['Grade'].value_counts().sort_index()

Grade
A     52
B    146
C    261
D    256
E    182
F    103
Name: count, dtype: int64